### ISSUE TITLE
No Event for CodePipeline

### ISSUE THREAD

**Issue by knizami** [aws/aws-lambda-java-libs#32] opened 2017-11-15 00:03 UTC
Are CodePipeline events supported for AWS Lambda?  When calling a Lambda function from CodePipeline, we were unable to define a CodePipelineEvent ourself that would work.  There are also no examples to be found on the internet.

**Comment by oharaandrew314** [comment] 2018-01-17 15:53
Dup of #16

**Comment by carlzogh** [comment] 2020-04-28 10:14
Closing as duplicate of https://github.com/aws/aws-lambda-java-libs/issues/16

**Closed by carlzogh** 2020-04-28 10:14 UTC
Labels: duplicate
