### ISSUE TITLE
Lambda throwing "Unable to parse Json String" when there is unhandled exception in lambda with a root cause chain

### ISSUE THREAD

**Issue by damodhar22** [aws/aws-lambda-java-libs#219] opened 2021-02-02 16:38 UTC
<b> Inconsistent behavior on unhandled exception in lambda</b>

1. When we throw a below exception lambda throws LambdaException with error error message "Error while processing"

`throw new RuntimeException("Error while processing")`

2. When we a below exception with cause lambda throws "com.amazonaws.SdkClientException: Unable to parse Json String"

`throw new RuntimeException("Error while processing", (Throwable)cause)`

Why are we seeing <b>com.amazonaws.SdkClientException: Unable to parse Json String</b> when code exits with handled exceptions with a cause chain? 

The expectation is that in the later case above the lambda should throw LambdaException with cause chain .

**Comment by smirnoal** [comment] 2024-09-03 11:34
I think this was fixed in recent versions of runtime-interface-client, and you should be able to see the cause in CW logs and X-ray console. Feel free to reach out if you still experience this problem

**Closed by smirnoal** 2024-09-03 11:34 UTC
